// <auto-generated />
using System;
using DmsContayPerezIPS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DmsContayPerezIPS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250913141706_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CentralUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer");

                    b.Property<long?>("FolderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GestionUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("TipoDocId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TipoDocumentalId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("FolderId");

                    b.HasIndex("TipoDocumentalId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.DocumentTag", b =>
                {
                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint");

                    b.HasKey("DocumentId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("DocumentTags");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.DocumentVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UploadedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("UploaderId")
                        .HasColumnType("bigint");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UploaderId");

                    b.ToTable("DocumentVersions");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.Folder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ParentId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.SerieDocumental", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Series");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Nombre = "Gestión Clínica"
                        },
                        new
                        {
                            Id = 2L,
                            Nombre = "Gestión Administrativa"
                        },
                        new
                        {
                            Id = 3L,
                            Nombre = "Gestión Financiera y Contable"
                        },
                        new
                        {
                            Id = 4L,
                            Nombre = "Gestión Jurídica"
                        },
                        new
                        {
                            Id = 5L,
                            Nombre = "Gestión de Calidad"
                        },
                        new
                        {
                            Id = 6L,
                            Nombre = "SG-SST"
                        },
                        new
                        {
                            Id = 7L,
                            Nombre = "Administración de equipos biomédicos"
                        });
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.SubserieDocumental", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DisposicionFinal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetencionCentral")
                        .HasColumnType("integer");

                    b.Property<int>("RetencionGestion")
                        .HasColumnType("integer");

                    b.Property<long>("SerieId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SerieId");

                    b.ToTable("Subseries");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DisposicionFinal = "Conservación total",
                            Nombre = "Historias clínicas",
                            RetencionCentral = 0,
                            RetencionGestion = 15,
                            SerieId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            DisposicionFinal = "Eliminación",
                            Nombre = "Incapacidades médicas",
                            RetencionCentral = 0,
                            RetencionGestion = 5,
                            SerieId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            DisposicionFinal = "Conservación total",
                            Nombre = "Contratos laborales",
                            RetencionCentral = 10,
                            RetencionGestion = 10,
                            SerieId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            DisposicionFinal = "Eliminación",
                            Nombre = "Correspondencia",
                            RetencionCentral = 0,
                            RetencionGestion = 2,
                            SerieId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            DisposicionFinal = "Conservación total",
                            Nombre = "Estados financieros",
                            RetencionCentral = 0,
                            RetencionGestion = 20,
                            SerieId = 3L
                        },
                        new
                        {
                            Id = 6L,
                            DisposicionFinal = "Eliminación",
                            Nombre = "Facturas",
                            RetencionCentral = 0,
                            RetencionGestion = 5,
                            SerieId = 3L
                        },
                        new
                        {
                            Id = 7L,
                            DisposicionFinal = "Conservación total",
                            Nombre = "Procesos judiciales",
                            RetencionCentral = 20,
                            RetencionGestion = 10,
                            SerieId = 4L
                        },
                        new
                        {
                            Id = 8L,
                            DisposicionFinal = "Actualización / Sustitución",
                            Nombre = "Manuales de procesos",
                            RetencionCentral = 0,
                            RetencionGestion = 5,
                            SerieId = 5L
                        },
                        new
                        {
                            Id = 9L,
                            DisposicionFinal = "Eliminación",
                            Nombre = "Registros de calidad",
                            RetencionCentral = 0,
                            RetencionGestion = 3,
                            SerieId = 5L
                        },
                        new
                        {
                            Id = 10L,
                            DisposicionFinal = "Conservación total",
                            Nombre = "Accidentes laborales",
                            RetencionCentral = 0,
                            RetencionGestion = 20,
                            SerieId = 6L
                        },
                        new
                        {
                            Id = 11L,
                            DisposicionFinal = "Eliminación",
                            Nombre = "Capacitaciones SST",
                            RetencionCentral = 0,
                            RetencionGestion = 5,
                            SerieId = 6L
                        },
                        new
                        {
                            Id = 12L,
                            DisposicionFinal = "Conservación mientras dure la vida útil",
                            Nombre = "Hojas de vida de equipos",
                            RetencionCentral = 0,
                            RetencionGestion = 0,
                            SerieId = 7L
                        },
                        new
                        {
                            Id = 13L,
                            DisposicionFinal = "Eliminación",
                            Nombre = "Mantenimientos",
                            RetencionCentral = 0,
                            RetencionGestion = 5,
                            SerieId = 7L
                        });
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.TipoDocumental", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DisposicionFinal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("RetencionCentral")
                        .HasColumnType("smallint");

                    b.Property<short>("RetencionGestion")
                        .HasColumnType("smallint");

                    b.Property<long>("SubserieId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubserieId");

                    b.ToTable("TiposDocumentales");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DisposicionFinal = "CT",
                            Nombre = "Historia de ingreso",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            DisposicionFinal = "CT",
                            Nombre = "Notas de evolución",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            DisposicionFinal = "CT",
                            Nombre = "Resultados de laboratorio",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            DisposicionFinal = "CT",
                            Nombre = "Certificado de incapacidad",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            DisposicionFinal = "CT",
                            Nombre = "Soporte médico",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            DisposicionFinal = "CT",
                            Nombre = "Contrato firmado",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 3L
                        },
                        new
                        {
                            Id = 7L,
                            DisposicionFinal = "CT",
                            Nombre = "Acta de terminación",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 3L
                        },
                        new
                        {
                            Id = 8L,
                            DisposicionFinal = "CT",
                            Nombre = "Carta enviada",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 4L
                        },
                        new
                        {
                            Id = 9L,
                            DisposicionFinal = "CT",
                            Nombre = "Carta recibida",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 4L
                        },
                        new
                        {
                            Id = 10L,
                            DisposicionFinal = "CT",
                            Nombre = "Balance general",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 5L
                        },
                        new
                        {
                            Id = 11L,
                            DisposicionFinal = "CT",
                            Nombre = "Estado de resultados",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 5L
                        },
                        new
                        {
                            Id = 12L,
                            DisposicionFinal = "CT",
                            Nombre = "Factura de proveedor",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 6L
                        },
                        new
                        {
                            Id = 13L,
                            DisposicionFinal = "CT",
                            Nombre = "Factura de cliente",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 6L
                        },
                        new
                        {
                            Id = 14L,
                            DisposicionFinal = "CT",
                            Nombre = "Demanda",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 7L
                        },
                        new
                        {
                            Id = 15L,
                            DisposicionFinal = "CT",
                            Nombre = "Sentencia",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 7L
                        },
                        new
                        {
                            Id = 16L,
                            DisposicionFinal = "CT",
                            Nombre = "Manual de calidad",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 8L
                        },
                        new
                        {
                            Id = 17L,
                            DisposicionFinal = "CT",
                            Nombre = "Registro de auditoría interna",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 9L
                        },
                        new
                        {
                            Id = 18L,
                            DisposicionFinal = "CT",
                            Nombre = "Reporte de accidente",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 10L
                        },
                        new
                        {
                            Id = 19L,
                            DisposicionFinal = "CT",
                            Nombre = "Lista de asistencia",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 11L
                        },
                        new
                        {
                            Id = 20L,
                            DisposicionFinal = "CT",
                            Nombre = "Ficha técnica del equipo",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 12L
                        },
                        new
                        {
                            Id = 21L,
                            DisposicionFinal = "CT",
                            Nombre = "Reporte de mantenimiento preventivo",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 13L
                        },
                        new
                        {
                            Id = 22L,
                            DisposicionFinal = "CT",
                            Nombre = "Reporte de mantenimiento correctivo",
                            RetencionCentral = (short)0,
                            RetencionGestion = (short)0,
                            SubserieId = 13L
                        });
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("DmsContayPerezIPS.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.Document", b =>
                {
                    b.HasOne("DmsContayPerezIPS.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("DmsContayPerezIPS.Domain.Entities.Folder", "Folder")
                        .WithMany("Documents")
                        .HasForeignKey("FolderId");

                    b.HasOne("DmsContayPerezIPS.Domain.Entities.TipoDocumental", "TipoDocumental")
                        .WithMany()
                        .HasForeignKey("TipoDocumentalId");

                    b.Navigation("Creator");

                    b.Navigation("Folder");

                    b.Navigation("TipoDocumental");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.DocumentTag", b =>
                {
                    b.HasOne("DmsContayPerezIPS.Domain.Entities.Document", "Document")
                        .WithMany("DocumentTags")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DmsContayPerezIPS.Domain.Entities.Tag", "Tag")
                        .WithMany("DocumentTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.DocumentVersion", b =>
                {
                    b.HasOne("DmsContayPerezIPS.Domain.Entities.Document", "Document")
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DmsContayPerezIPS.Domain.Entities.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId");

                    b.Navigation("Document");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.Folder", b =>
                {
                    b.HasOne("DmsContayPerezIPS.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("DmsContayPerezIPS.Domain.Entities.Folder", "Parent")
                        .WithMany("Subfolders")
                        .HasForeignKey("ParentId");

                    b.Navigation("Creator");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.SubserieDocumental", b =>
                {
                    b.HasOne("DmsContayPerezIPS.Domain.Entities.SerieDocumental", "Serie")
                        .WithMany("Subseries")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.TipoDocumental", b =>
                {
                    b.HasOne("DmsContayPerezIPS.Domain.Entities.SubserieDocumental", "Subserie")
                        .WithMany("Tipos")
                        .HasForeignKey("SubserieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subserie");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.User", b =>
                {
                    b.HasOne("DmsContayPerezIPS.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.Document", b =>
                {
                    b.Navigation("DocumentTags");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.Folder", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Subfolders");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.SerieDocumental", b =>
                {
                    b.Navigation("Subseries");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.SubserieDocumental", b =>
                {
                    b.Navigation("Tipos");
                });

            modelBuilder.Entity("DmsContayPerezIPS.Domain.Entities.Tag", b =>
                {
                    b.Navigation("DocumentTags");
                });
#pragma warning restore 612, 618
        }
    }
}
